spring:
  datasource:
    name: red
    url: jdbc:mysql://127.0.0.1:3306/red?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #不占用 8080端口，有 spring-boot-starter-web jar或者tomcat 集成jar都需要启动 8080
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  dubbo:
    application:
      name:  business-provider
    registry:
      protocol: zookeeper
      address: 192.168.238.136:2181
    protocol:
      name: dubbo
      port: 20880
      host: localhost
    scan: com.shi.main.provider
  redis:
    database: 0
    host: 192.168.238.136
    port: 6379
    jedis:
      pool:
        max-active: 8 #连接池的最大连接数
        max-idle: 8 #连接池的最大空闲连接数
        max-wait: -1ms #连接池最大阻塞等待时间 默认为-1，没有限制
        min-idle: 0 # 连接池的最小连接数
logging:
  file:
    path: log\redPacket.log
  level:
    com: debug
